
Organizations:

    
    - &OrdererOrg
       
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../organizations/ordererOrganizations/example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

        OrdererEndpoints:
            - orderer.example.com:7050

    - &issuerOrg
        
        Name: issuerOrgMSP
        ID: issuerOrgMSP
        MSPDir: ../organizations/peerOrganizations/issuerOrg.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('issuerOrgMSP.admin', 'issuerOrgMSP.peer', 'issuerOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('issuerOrgMSP.admin', 'issuerOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('issuerOrgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('issuerOrgMSP.peer')"

    - &verifyingOrg
        
        Name: verifyingOrgMSP
        ID: verifyingOrgMSP
        MSPDir: ../organizations/peerOrganizations/verifyingOrg.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('verifyingOrgMSP.admin', 'verifyingOrgMSP.peer', 'verifyingOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('verifyingOrgMSP.admin', 'verifyingOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('verifyingOrgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('verifyingOrgMSP.peer')"
    
    - &peerOrg
        
        Name: peerOrgMSP
        ID: peerOrgMSP
        MSPDir: ../organizations/peerOrganizations/peerOrg.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('peerOrgMSP.admin', 'peerOrgMSP.peer', 'peerOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('peerOrgMSP.admin', 'peerOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('peerOrgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('peerOrgMSP.peer')"

Capabilities:
    
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

    OrdererType: etcdraft
  
    Addresses:
        - orderer.example.com:7050

    EtcdRaft:
        Consenters:
        - Host: orderer.example.com
          Port: 7050
          ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
          ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
 
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults

    Policies:

        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    TwoOrgsApplicationGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
            Capabilities: *ApplicationCapabilities
